# Generated by Django 3.1.7 on 2021-05-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserScan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmap',
            name='scan_type',
            field=models.CharField(default='SynScan', max_length=50),
        ),
        migrations.AlterField(
            model_name='nmap',
            name='port',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='nmap',
            name='state',
            field=models.CharField(max_length=5000),
        ),
    ]
