# Generated by Django 3.2.3 on 2021-06-04 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserScan', '0002_auto_20210512_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='who_is',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.TextField()),
                ('registrar', models.TextField()),
                ('whois_server', models.TextField()),
                ('referral_url', models.TextField()),
                ('updated_date', models.TextField()),
                ('creation_date', models.TextField()),
                ('expiration_date', models.TextField()),
                ('name_servers', models.TextField()),
                ('status', models.TextField()),
                ('emails', models.TextField()),
                ('dnssec', models.TextField()),
                ('name', models.TextField()),
                ('org', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.TextField()),
                ('country', models.TextField()),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
