# Generated by Django 3.2.3 on 2021-06-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserScan', '0003_who_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who_is',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='creation_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='dnssec',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='domain_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='emails',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='expiration_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='name_servers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='org',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='referral_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='registrar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='state',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='updated_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='whois_server',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='who_is',
            name='zipcode',
            field=models.TextField(null=True),
        ),
    ]
